feat: add README.md

diff --git a/dot b/dot
--- a/dot
+++ b/dot
@@ -2,22 +2,27 @@
 # This script was generated by bashly 1.1.8 (https://bashly.dannyb.co)
 # Modifying it manually is not recommended
 
+# :wrapper.bash3_bouncer
 if [[ "${BASH_VERSINFO:-0}" -lt 4 ]]; then
   printf "bash version 4 or higher is required\n" >&2
   exit 1
 fi
 
+# :command.master_script
+
+# :command.version_command
 version_command() {
   echo "$version"
 }
 
+# :command.usage
 dot_usage() {
   if [[ -n $long_usage ]]; then
-    printf "dot - dotfiles manager based on stow\n"
+    printf "dot - dotfiles manager\n"
     echo
 
   else
-    printf "dot - dotfiles manager based on stow\n"
+    printf "dot - dotfiles manager\n"
     echo
 
   fi
@@ -27,7 +32,7 @@ dot_usage() {
   printf "  dot [COMMAND] --help | -h\n"
   printf "  dot --version | -v\n"
   echo
-
+  # :command.usage_commands
   printf "%s\n" "Commands:"
   printf "  %s   Show help about a command\n" "help  "
   printf "  %s   Create a link to the dot script\n" "link  "
@@ -39,9 +44,11 @@ dot_usage() {
   printf "  %s   Clone a remote git dotfiles repository\n" "clone "
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
@@ -49,21 +56,25 @@ dot_usage() {
     printf "    Show version number\n"
     echo
 
+    # :command.usage_environment_variables
     printf "%s\n" "Environment Variables:"
 
+    # :environment_variable.usage
     printf "  %s\n" "DOT_INSTALL_DIR"
     printf "    Directory where the repository was cloned\n"
     printf "    Default: ${HOME}/.dot\n"
     echo
 
+    # :environment_variable.usage
     printf "  %s\n" "DOT_DOTFILES_DIR"
-    printf "    Directory where the projects will be managed\n"
+    printf "    Directory where the dotfiles were cloned\n"
     printf "    Default: ${HOME}/dotfiles\n"
     echo
 
   fi
 }
 
+# :command.usage
 dot_help_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot help - Show help about a command\n"
@@ -80,15 +91,19 @@ dot_help_usage() {
   printf "  dot help --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_args
     printf "%s\n" "Arguments:"
 
+    # :argument.usage
     printf "  %s\n" "COMMAND"
     printf "    Help subject\n"
     echo
@@ -96,6 +111,7 @@ dot_help_usage() {
   fi
 }
 
+# :command.usage
 dot_clone_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot clone - Clone a remote git dotfiles repository\n"
@@ -112,19 +128,24 @@ dot_clone_usage() {
   printf "  dot clone --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_args
     printf "%s\n" "Arguments:"
 
+    # :argument.usage
     printf "  %s\n" "REPOSITORY"
     printf "    Remote repository to clone (FORMAT: <username>/<repository>)\n"
     echo
 
+    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  dot clone alexis-moins/dotfiles\n"
     echo
@@ -132,6 +153,7 @@ dot_clone_usage() {
   fi
 }
 
+# :command.usage
 dot_link_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot link - Create a link to the dot script\n"
@@ -148,24 +170,31 @@ dot_link_usage() {
   printf "  dot link --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_flags
+    # :flag.usage
     printf "  %s\n" "--copy, -c"
     printf "    Copy the script instead of creating a symbolic link\n"
     echo
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_args
     printf "%s\n" "Arguments:"
 
+    # :argument.usage
     printf "  %s\n" "PATH"
     printf "    Path to the link\n"
     printf "    Default: ${HOME}/.local/bin\n"
     echo
 
+    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  dot link -c\n"
     printf "  dot link /usr/bin\n"
@@ -174,6 +203,7 @@ dot_link_usage() {
   fi
 }
 
+# :command.usage
 dot_unlink_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot unlink - Remove the link to the dot script\n"
@@ -190,20 +220,25 @@ dot_unlink_usage() {
   printf "  dot unlink --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_args
     printf "%s\n" "Arguments:"
 
+    # :argument.usage
     printf "  %s\n" "PATH"
     printf "    Path to the link\n"
     printf "    Default: ${HOME}/.local/bin\n"
     echo
 
+    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  dot unlink\n"
     echo
@@ -211,6 +246,7 @@ dot_unlink_usage() {
   fi
 }
 
+# :command.usage
 dot_update_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot update - Update to the latest version\n"
@@ -227,13 +263,16 @@ dot_update_usage() {
   printf "  dot update --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  dot update\n"
     echo
@@ -241,6 +280,7 @@ dot_update_usage() {
   fi
 }
 
+# :command.usage
 dot_env_usage() {
   if [[ -n $long_usage ]]; then
     printf "dot env - Show environment information\n"
@@ -257,13 +297,16 @@ dot_env_usage() {
   printf "  dot env --help | -h\n"
   echo
 
+  # :command.long_usage
   if [[ -n $long_usage ]]; then
     printf "%s\n" "Options:"
 
+    # :command.usage_fixed_flags
     printf "  %s\n" "--help, -h"
     printf "    Show this help\n"
     echo
 
+    # :command.usage_examples
     printf "%s\n" "Examples:"
     printf "  dot env\n"
     echo
@@ -271,6 +314,7 @@ dot_env_usage() {
   fi
 }
 
+# :command.normalize_input
 normalize_input() {
   local arg flags
 
@@ -295,6 +339,48 @@ normalize_input() {
   done
 }
 
+# :command.inspect_args
+inspect_args() {
+  if ((${#args[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!args[@]}" | sort)
+    echo args:
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${args[$k]} = ${args[$k]}"
+    done
+  else
+    echo args: none
+  fi
+
+  if ((${#other_args[@]})); then
+    echo
+    echo other_args:
+    echo "- \${other_args[*]} = ${other_args[*]}"
+    for i in "${!other_args[@]}"; do
+      echo "- \${other_args[$i]} = ${other_args[$i]}"
+    done
+  fi
+
+  if ((${#deps[@]})); then
+    readarray -t sorted_keys < <(printf '%s\n' "${!deps[@]}" | sort)
+    echo
+    echo deps:
+    for k in "${sorted_keys[@]}"; do
+      echo "- \${deps[$k]} = ${deps[$k]}"
+    done
+  fi
+
+  if ((${#env_var_names[@]})); then
+    readarray -t sorted_names < <(printf '%s\n' "${env_var_names[@]}" | sort)
+    echo
+    echo "environment variables:"
+    for k in "${sorted_names[@]}"; do
+      echo "- \$$k = ${!k:-}"
+    done
+  fi
+}
+
+# :command.user_lib
+# src/lib/colors.sh
 print_in_color() {
   local color="$1"
   shift
@@ -326,19 +412,25 @@ blue_underlined() { print_in_color "\e[4;34m" "$*"; }
 magenta_underlined() { print_in_color "\e[4;35m" "$*"; }
 cyan_underlined() { print_in_color "\e[4;36m" "$*"; }
 
+# src/lib/log/error.sh
 error() {
     gum log --level="error" --prefix="pm" --prefix.foreground="7" --level.foreground="1" "${1}"
 }
 
+# src/lib/log/info.sh
 info() {
     gum log --level="error" --prefix="pm" --prefix.foreground="7" --level.foreground="4" "${1}"
 }
 
+# src/lib/log/warn.sh
 warn() {
     gum log --level="warn" --prefix="pm" --prefix.foreground="7" --level.foreground="3" "${1}"
 }
 
+# :command.command_functions
+# :command.function
 dot_help_command() {
+  # src/help_command.sh
   command="${args[command]:-}"
   long_usage=yes
 
@@ -360,7 +452,9 @@ dot_help_command() {
 
 }
 
+# :command.function
 dot_clone_command() {
+  # src/clone_command.sh
   local repository="${args[repository]}"
 
   if [[ -d "${DOT_DOTFILES_DIR}" ]]; then
@@ -374,7 +468,9 @@ dot_clone_command() {
 
 }
 
+# :command.function
 dot_link_command() {
+  # src/link_command.sh
   local path="${args[path]}"
   local copy="${args[--copy]}"
 
@@ -402,7 +498,9 @@ dot_link_command() {
 
 }
 
+# :command.function
 dot_unlink_command() {
+  # src/unlink_command.sh
   local path="${args[path]}"
 
   if [[ -f "${path}/dot" ]]; then
@@ -416,7 +514,9 @@ dot_unlink_command() {
 
 }
 
+# :command.function
 dot_update_command() {
+  # src/update_command.sh
   if [[ ! -d "${DOT_INSTALL_DIR}" ]]; then
       warn "no dot install directory."
       warn "check documentation for installation instruction."
@@ -427,14 +527,17 @@ dot_update_command() {
 
 }
 
+# :command.function
 dot_env_command() {
+  # src/env_command.sh
   echo "DOT_INSTALL_DIR=${DOT_INSTALL_DIR}"
   echo "DOT_DOTFILES_DIR=${DOT_DOTFILES_DIR}"
 
 }
 
+# :command.parse_requirements
 parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --version | -v)
@@ -455,23 +558,19 @@ parse_requirements() {
     esac
   done
 
+  # :command.environment_variables_filter
+  # :command.environment_variables_default
   export DOT_INSTALL_DIR="${DOT_INSTALL_DIR:-${HOME}/.dot}"
   export DOT_DOTFILES_DIR="${DOT_DOTFILES_DIR:-${HOME}/dotfiles}"
 
   env_var_names+=("DOT_INSTALL_DIR")
   env_var_names+=("DOT_DOTFILES_DIR")
 
+  # :command.dependencies_filter
   if command -v git >/dev/null 2>&1; then
     deps['git']="$(command -v git | head -n1)"
   else
     printf "missing dependency: git\n" >&2
-    exit 1
-  fi
-
-  if command -v fd >/dev/null 2>&1; then
-    deps['fd']="$(command -v fd | head -n1)"
-  else
-    printf "missing dependency: fd\n" >&2
     exit 1
   fi
 
@@ -482,13 +581,14 @@ parse_requirements() {
     exit 1
   fi
 
-  if command -v rg >/dev/null 2>&1; then
-    deps['rg']="$(command -v rg | head -n1)"
+  if command -v stow >/dev/null 2>&1; then
+    deps['stow']="$(command -v stow | head -n1)"
   else
-    printf "missing dependency: rg\n" >&2
+    printf "missing dependency: stow\n" >&2
     exit 1
   fi
 
+  # :command.command_filter
   action=${1:-}
 
   case $action in
@@ -536,6 +636,7 @@ parse_requirements() {
       shift $#
       ;;
 
+    # :command.command_fallback
     "")
       dot_usage >&2
       exit 1
@@ -548,6 +649,7 @@ parse_requirements() {
 
   esac
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -558,7 +660,8 @@ parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -569,8 +672,9 @@ parse_requirements() {
 
 }
 
+# :command.parse_requirements
 dot_help_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -586,8 +690,10 @@ dot_help_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="help"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -598,7 +704,8 @@ dot_help_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         if [[ -z ${args['command']+x} ]]; then
           args['command']=$1
           shift
@@ -614,8 +721,9 @@ dot_help_parse_requirements() {
 
 }
 
+# :command.parse_requirements
 dot_clone_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -631,8 +739,10 @@ dot_clone_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="clone"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -643,7 +753,8 @@ dot_clone_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         if [[ -z ${args['repository']+x} ]]; then
           args['repository']=$1
           shift
@@ -657,6 +768,7 @@ dot_clone_parse_requirements() {
     esac
   done
 
+  # :command.required_args_filter
   if [[ -z ${args['repository']+x} ]]; then
     printf "missing required argument: REPOSITORY\nusage: dot clone REPOSITORY\n" >&2
     exit 1
@@ -664,8 +776,9 @@ dot_clone_parse_requirements() {
 
 }
 
+# :command.parse_requirements
 dot_link_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -681,14 +794,17 @@ dot_link_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="link"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
-
+      # :flag.case
       --copy | -c)
 
+        # :flag.case_no_arg
         args['--copy']=1
         shift
         ;;
@@ -699,7 +815,8 @@ dot_link_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         if [[ -z ${args['path']+x} ]]; then
           args['path']=$1
           shift
@@ -713,12 +830,14 @@ dot_link_parse_requirements() {
     esac
   done
 
+  # :command.default_assignments
   [[ -n ${args['path']:-} ]] || args['path']="${HOME}/.local/bin"
 
 }
 
+# :command.parse_requirements
 dot_unlink_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -734,8 +853,10 @@ dot_unlink_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="unlink"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -746,7 +867,8 @@ dot_unlink_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         if [[ -z ${args['path']+x} ]]; then
           args['path']=$1
           shift
@@ -760,12 +882,14 @@ dot_unlink_parse_requirements() {
     esac
   done
 
+  # :command.default_assignments
   [[ -n ${args['path']:-} ]] || args['path']="${HOME}/.local/bin"
 
 }
 
+# :command.parse_requirements
 dot_update_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -781,8 +905,10 @@ dot_update_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="update"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -793,7 +919,8 @@ dot_update_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -804,8 +931,9 @@ dot_update_parse_requirements() {
 
 }
 
+# :command.parse_requirements
 dot_env_parse_requirements() {
-
+  # :command.fixed_flags_filter
   while [[ $# -gt 0 ]]; do
     case "${1:-}" in
       --help | -h)
@@ -821,8 +949,10 @@ dot_env_parse_requirements() {
     esac
   done
 
+  # :command.command_filter
   action="env"
 
+  # :command.parse_requirements_while
   while [[ $# -gt 0 ]]; do
     key="$1"
     case "$key" in
@@ -833,7 +963,8 @@ dot_env_parse_requirements() {
         ;;
 
       *)
-
+        # :command.parse_requirements_case
+        # :command.parse_requirements_case_simple
         printf "invalid argument: %s\n" "$key" >&2
         exit 1
 
@@ -844,16 +975,19 @@ dot_env_parse_requirements() {
 
 }
 
+# :command.initialize
 initialize() {
   version="0.1.0"
   long_usage=''
   set -e
 
+  # :command.environment_variables_default
   export DOT_INSTALL_DIR="${DOT_INSTALL_DIR:-${HOME}/.dot}"
   export DOT_DOTFILES_DIR="${DOT_DOTFILES_DIR:-${HOME}/dotfiles}"
 
 }
 
+# :command.run
 run() {
   declare -A args=()
   declare -A deps=()
